version: "3.8"
services:
  mongodb:
    image: mongo:6.0
    container_name: mean_mongo
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: examplepassword
    networks:
      - mean-net

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: sachushiljad/mean-backend:latest
    container_name: mean_backend
    restart: unless-stopped
    environment:
      PORT: 3000
      MONGO_URI: mongodb://root:examplepassword@mongodb:27017/mean_db?authSource=admin
    depends_on:
      - mongodb
    networks:
      - mean-net
    expose:
      - "3000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: sachushiljad/mean-frontend:latest
    container_name: mean_frontend
    restart: unless-stopped
    networks:
      - mean-net
    expose:
      - "80"

  nginx-proxy:
    image: nginx:stable-alpine
    container_name: mean_nginx_proxy
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
    networks:
      - mean-net

volumes:
  mongo_data:

networks:
  mean-net:
    driver: bridge
